blank_issues_enabled: false
contact_links:
  - name: Transparency.dev Slack
    url: https://transparency.dev/slack/
    about: Also consider our Slack channel. It's the quickest way to have a conversation with the developers!
